site_name: spangle - ASGI framework for modern web application
site_url: "https://tkamenoko.github.io/spangle/"

repo_url: "https://github.com/tkamenoko/spangle/"
edit_uri: ""

theme:
  name: "material"
  feature:
    - tabs
    - instant
  icon:
    logo: octicons/north-star-16
    repo: octicons/mark-github-16
  palette:
    primary: "teal"
    accent: "pink"

markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: True
  - extra
  - smarty
  - codehilite:
      linenums: true
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true
  - inari:
      module: spangle
      out-name: api
